{% set version = "1.1.9" %}

package:
  name: sphinxcontrib-serializinghtml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinxcontrib-serializinghtml/sphinxcontrib_serializinghtml-{{ version }}.tar.gz
  sha256: 0c64ff898339e1fac29abd2bf5f11078f3ec413cfe9c046d3120d7ca65530b54

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - flit-core
  run:
    - python
    - sphinx >=5

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.serializinghtml
  requires:
    - pip
    # This is a circular dependency b/c sphinx depends on this package now :-/
    - sphinx
  commands:
    # pip check incorrectly shows dependencies for sphinx 4.0.1
    - pip check

about:
  home: http://sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-serializinghtml

extra:
  recipe-maintainers:
    - ocefpaf
